spring.application.name: officeflow
spring:
  datasource:
    url: jdbc:postgresql://db:5432/office-flow-db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: user
      password: user123
      roles: USER
autoconfigure:
  exclude:
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  servlet:
    multipart:
      enabled: true
logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type: off

