services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_LOCATION: /config/application.yml  # Especifica o local do arquivo de propriedades
    depends_on:
      - db
    volumes:
      - ./application.release.yml:/config/application.yml  # Mapeia o arquivo
    networks:
      - office-flow_network
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: office-flow-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - office-flow_network

volumes:
  pg_data:

networks:
  office-flow_network: