services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: office-flow-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - office-flow_network

volumes:
  pg_data:

networks:
  office-flow_network: